import React from "react";
import Navbar from "@/components/Navbar";
import SearchHeader from "./components/SearchHeader";
import SearchSidebar from "./components/SearchSidebar";
import SearchCard from "./components/SearchCard";
import { PRICE, PrismaClient } from "@prisma/client";
import { Metadata } from "next";

export const metadata: Metadata = {
  title: "search",
  description: "Generated by create next app",
  keywords: ["aryan", "page"],
};

const prisma = new PrismaClient();

const fetchLocations = () => {
  return prisma.location.findMany();
};

const fetchRegions = () => {
  return prisma.region.findMany();
};

const fetchRestaurant = (city: string | undefined) => {
  const select = {
    id: true,
    name: true,
    main_image: true,
    price: true,
    location: true,
    region: true,
    slug: true,
  };

  if (!city)
    return prisma.restaurant.findMany({
      select,
    });
  return prisma.restaurant.findMany({
    where: {
      location: {
        name: {
          equals: city.toLocaleLowerCase(),
        },
      },
    },
    select,
  });
};

export default async function page({
  searchParams,
}: {
  searchParams: { city?: string; region?: string; price?: PRICE };
}) {
  // console.log(props)
  const restaurants = await fetchRestaurant(searchParams.city);
  // console.log(restaurants)

  const locations = await fetchLocations();
  const regions = await fetchRegions();

  return (
    <main className="bg-gray-100 min-h-screen w-screen">
      <main className="max-w-screen-2xl m-auto bg-white">
        <Navbar />
        <SearchHeader />
        <div className="flex py-4 m-auto w-2/3 justify-between items-start">
          <SearchSidebar locations={locations} regions={regions} searchParams={searchParams}/>
          <div className="w-5/6">
            {restaurants.length ? (
              restaurants.map((restaurant) => (
                <SearchCard restaurant={restaurant} />
              ))
            ) : (
              <p>Sorry no restaurant found !!</p>
            )}
          </div>
        </div>
      </main>
    </main>
  );
}
